apiVersion: v1
kind: Service
metadata:
  name: namegen-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-class: "://amazonaws.com"
spec:
  type: LoadBalancer
  selector:
    app: namegen 
  ports:
    - port: 80        
      targetPort: 8080 
      nodePort: 30080
      protocol: TCP
