apiVersion: apps/v1
kind: Deployment
metadata:
  name: namegen
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: namegen
  template:
    metadata:
      labels:
        app: namegen
    spec:
      containers:
        - name: namegen
          image: ://amazonaws.com 
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              value: "mongodb://genuser:$(MONGO_ROOT_PASSWORD)@mongodb:27017/namegen?authSource=admin"
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
