name: "DevOps Destroy Pipeline"

on:
  workflow_dispatch:
    inputs:
      destroy_scope:
        description: 'Choose what to delete from AWS to save money:'
        required: true
        default: 'expensive_only'
        type: choice
        options:
          - 'expensive_only' 
          - 'everything'     
jobs:
  infrastructure_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-eks-deploy-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Destroy (Expensive Components Only)
        if: ${{ github.event.inputs.destroy_scope == 'expensive_only' }}
        run: |
          cd terraform
          terraform destroy -target=aws_eks_cluster.eks_cluster -target=module.vpc.aws_nat_gateway.this -auto-approve

      - name: Terraform Destroy (Everything)
        if: ${{ github.event.inputs.destroy_scope == 'everything' }}
        run: |
          cd terraform
          terraform destroy -auto-approve
